#!/usr/bin/sh

# This script requires ETH_PRIVATE_KEY, ETH_RPC_URL and TROLLUP_L1_CONTRACT to be set in the environment.

echo "Starting sequencer/prover..."
$(cd trollup-sequencer && nohup cargo run --release > nohup_trollup.out)&
sleep 2
